version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # This is not recommended for production. In production, use proper authentication methods
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5430:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - laccount-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - laccount-network

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_db:/var/lib/mysql
  #   networks:
  #     - laccount-network

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: phpmyadmin
  #   ports:
  #     - "8181:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   depends_on:
  #     - mysql
  #   networks:
  #     - laccount-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_dir:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - laccount-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_db:/data
    networks:
      - laccount-network

  # Uncomment and customize the application service as needed
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: laccount-app
  #   restart: always
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports:
  #     - "3500:3000"
  #   environment:
  #     REDIS_URI: ${REDIS_URI}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_HOST: postgres
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #     SMTP_HOST: ${SMTP_HOST}
  #     SMTP_PORT: ${SMTP_PORT}
  #     SMTP_USER: ${SMTP_USER}
  #     SMTP_PASSWORD: ${SMTP_PASSWORD}
  #     RABBITMQ_HOST: rabbitmq
  #     RABBITMQ_USER: ${RABBITMQ_USER}
  #     RABBITMQ_PASS: ${RABBITMQ_PASS}
  #   volumes:
  #     - .:/app
  #   networks:
  #     - laccount-network

networks:
  laccount-network:

volumes:
  mysql_db:
  postgres_db:
  redis_db:
  rabbitmq_dir:
