# FROM node:21
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "run", "start:dev"]



# # Use an official lightweight Bun image or Node.js image and install Bun
# FROM oven/bun:latest AS builder

# # Set working directory
# WORKDIR /app

# # Copy package.json, bun.lockb (if you have one), and source files
# COPY . .

# # Install dependencies with Bun
# RUN bun install

# # Expose the application port
# EXPOSE 3500

# # Start the app using Bun
# CMD ["bun", "run", "start"]